apiVersion: v1
kind: Secret
metadata:
  name: my-repo-ssh
  # namespace: argocd
  labels:
    # argocd.argoproj.io/secret-type: repo-creds
    # for connect stat use use this label
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: ssh://git@192.168.99.100:2222/root/gitops.git
  sshPrivateKey: ""
  # optional
  name: helm-gitops-repo
  # k get appprojects.argoproj.io -n argocd (also in UI)
  project: default
