resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.3/manifests/install.yaml
  - ./argocd-server-ingress.yaml  # add your own manifest
  - ./argocd-custom-secret.yaml

patches:
  - path: ./argocd-cm-params-patch.yaml  # patch a existing manifest
  - path: ./argocd-cm-patch.yaml
  - path: ./argocd-cm-ssh-patch.yaml

  # - path: argocd-rbac-cm-patch.yaml
  # - path: ./argocd-server-patch.yaml

images:
  - name: public.ecr.aws/docker/library/redis:8.2.3-alpine  # what need to change
    newName: docker.io/library/redis                        # new full image name
    newTag: 8.2.3-alpine3.22                                # new tag

