apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprod-applications
spec:
  destination:
    namespace: preprod
    server: https://kubernetes.default.svc
  source:
    path: ./values/stands/preprod
    repoURL: ssh://git@192.168.99.100:2222/root/gitops.git
    targetRevision: feature/WBR-001
  sources: []
  project: default
  syncPolicy:
    automated: null

