fullnameOverride: hash-generator

app:
  image:
    repository: 192.168.99.100:5050/root/hash-generator
    tag: 1.2.0
    digest: 299008ae70cef8a381991f89989ca6830a16853eb27077a04485929b9cd829eb
  replicas: 1
  port: 3000
  envs:
    REQUEST_ENDPOINT: "echo"
    TARGET_URL: "http://echo-server.prod.svc:3000"
  probes:
    readiness:
      enabled: true
      path: /ready
      periodSeconds: 15

ingress:
  enabled: true
  hosts:
    - host: hash-generator.prod.local
      paths:
        - path: /
          pathType: Prefix

vault:
  address: http://vault-svc.vault.svc:8200
  role: vault-auth-prod-hash-generator
  serviceAccountName: hash-generator
  secret:
    enginePath: secrets/prod/hash-generator
    name: config
    type: kv-v2
  vso:
    enabled: true

