apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../../base

configMapGenerator:
  - name: hash-generator-config
    files:
      - ./cfg/application.yaml
      - ./cfg/logback.xml

helmGlobals:
  chartHome: ../../../../

helmCharts:
  - name: chart
    releaseName: hash-generator
    valuesFile: ../../../../chart/values.base.yaml
    additionalValuesFiles:
      - ../../../../base/values.yaml
      - ../../../dev-values.yaml
      - ./values.yaml

