apiVersion: v1
kind: Pod
metadata:
  name: echo-server-pod
  namespace: echo-server
spec:
  imagePullSecrets:
    - name: <img-pull-secrets> #
  containers:
    - name: echo-server
      image: <image> #
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: 25Mi
          cpu: 100m
        limits:
          memory: 25Mi
          cpu: 100m
      env:
        - name: TZ
          value: Europe/Moscow
      # ports:
      #   - containerPort: 3000
      #     name: es-port
