---
- name: Prerequisites (packages, timezone, swap, modules, sysctl)
  become: true
  any_errors_fatal: true
  block:
    - name: Create keyring dir if not exist
      ansible.builtin.file:
        path: /etc/apt/keyrings
        recurse: true
        state: directory

    - name: Set timezone to Europe/Moscow.
      community.general.timezone:
        name: Europe/Moscow

    - name: Disable swap.
      ansible.builtin.command: swapoff -a
      changed_when: true
      when: ansible_facts['swaptotal_mb'] > 0

    - name: Remove swap from fstab.
      ansible.builtin.lineinfile:
        path: '/etc/fstab'
        regexp: '\sswap\s'
        state: 'absent'

    - name: Add a new entry to /etc/hosts
      when: k8s_add_registry_domain_to_hosts | bool
      ansible.builtin.blockinfile:
        path: /etc/hosts
        append_newline: true
        prepend_newline: true
        block: |
          {% if k8s_insecure_registry.enabled %}
          {{ k8s_insecure_registry.ip }} {{ k8s_insecure_registry.dns_name }}
          {% else %}
          {{ k8s_secure_registry.ip }} {{ k8s_secure_registry.name }}
          {{ k8s_secure_registry.ip }} lab.myregistry.ru # in my case could not resolved the name when pull. idk why (rm the line in your case)
          {% endif %}
        insertafter: EOF

    # using with_items or loop means apt will be called for each package in the list independently.
    # below method improve install speed
    - name: Deps.
      ansible.builtin.apt:
        name: "{{ k8s_prerequisites_packages }}"
        state: present
        install_recommends: false
        update_cache: true

    - name: Modprobe modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
        # persistent: present
      with_items: "{{ k8s_container_and_network_modules }}"

    # Add modules to the single file persistent
    - name: Write modules to file
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
        mode: "0644"
        create: true
      with_items: "{{ k8s_container_and_network_modules }}"

    - name: Set sysctl options k8s
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/k8s.conf
        sysctl_set: true
        state: present
      with_items:
        - { name: "net.bridge.bridge-nf-call-iptables", value: 1 }
        - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
        - { name: "net.ipv4.ip_forward", value: 1 }


    - name: Disable IPv6 completely
      when: k8s_disable_ipv6
      block:
        - name: Remove IPv6 entries from /etc/hosts
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: '::'
            state: absent

        # - name: Configure systemd-resolved for IPv4
        #   ansible.builtin.lineinfile:
        #     path: /etc/systemd/resolved.conf
        #     regexp: "^{{ item.key }}="
        #     line: "{{ item.key }}={{ item.value }}"
        #     state: present
        #   loop:
        #     - { key: "DNS", value: "8.8.8.8 1.1.1.1" }
        #     - { key: "IPv6AcceptRA", value: "no" }

        - name: Change proority from IPv6 to IPv4
          ansible.builtin.lineinfile:
            path: /etc/gai.conf
            line: "precedence ::ffff:0:0/96  100"
            state: absent
            create: true

        - name: Disable IPv6 via sysctl
          ansible.posix.sysctl:
            name: "{{ item.name }}"
            value: "{{ item.value }}"
            sysctl_file: /etc/sysctl.d/60-ipv6-disable.conf
            sysctl_set: true
            state: present
          with_items:
            - { name: "net.ipv6.conf.all.disable_ipv6", value: 1 }
            - { name: "net.ipv6.conf.default.disable_ipv6", value: 1 }
            - { name: "net.ipv6.conf.lo.disable_ipv6", value: 1 }

        # - name: Flush systemd-resolved cache
        #   ansible.builtin.command: resolvectl flush-caches
        #   changed_when: false

        # - name: Restart systemd-resolved (clear dns cache)
        #   ansible.builtin.systemd:
        #     name: "{{ item }}"
        #     state: restarted
        #   with_items:
        #     - systemd-resolved
        #     - systemd-networkd

    - name: Disable systemd-resolved
      when: k8s_disable_systemd_resolved
      block:
        - name: Stop kube services.
          ignore_errors: true
          ansible.builtin.systemd_service:
            name: systemd-resolved
            state: stopped
            enabled: false
            masked: true

        - name: Remove existing resolv.conf (symlink or file)
          ansible.builtin.file:
            path: /etc/resolv.conf
            state: absent

        - name: Add dns to resolv.conf
          ansible.builtin.copy:
            dest: /etc/resolv.conf
            content: |
              nameserver {{ ansible_facts['default_ipv4']['gateway'] }}
            mode: "0555"

        - name: Restart systemd-networkd
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: restarted
          with_items:
            - systemd-networkd

    - name: IPVS mode setup
      when: k8s_ipvs_enable
      block:
        - name: Modprobe IPVS modules
          community.general.modprobe:
            name: "{{ item }}"
            state: present
          with_items: "{{ k8s_ipvs_modules }}"

        - name: Write modules to file
          ansible.builtin.lineinfile:
            path: /etc/modules-load.d/k8s-ipvs.conf
            line: "{{ item }}"
            mode: "0644"
            create: true
          with_items: "{{ k8s_ipvs_modules }}"
