apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preprod

resources:
  - ../../../../base

configMapGenerator:
  - name: echo-server-config
    files:
      - ./cfg/application.yaml
      - ./cfg/logback.xml

helmGlobals:
  chartHome: ../../../../

helmCharts:
  - name: chart
    releaseName: echo-server
    valuesFile: ../../../../chart/values.base.yaml
    additionalValuesFiles:
      - ../../../../base/values.yaml
      - ../../../preprod-values.yaml
      - ./values.yaml

