{{- include "ms.validateAll" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ms.rs }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.ms.update.maxUnavailable }}
      maxSurge: {{ .Values.ms.update.maxSurge }}
  selector:
    matchLabels:
      {{- include "ms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ms.selectorLabels" . | nindent 8 }}
        {{- with .Values.ms.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false # prevent mount /run/**/secrets
      {{- if .Values.ms.vaultSecrets.enabled }}
      serviceAccountName: {{ .Values.ms.vaultSecrets.role }} # SA для чтения из vault
      {{- end }}
      {{- with .Values.ms.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      {{- include "myhlp.vault_secrets_init_container" . | nindent 6 -}}
      containers:
        - name: {{ include "ms.fullname" . }}
          image: "{{ .Values.ms.repository }}:{{ .Values.ms.tag }}@sha256:{{ .Values.ms.digest }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true # Блокирует запись везде кроме /tmp и монтируемых volume
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: {{ .Values.ms.resources.requests.memory }}
              cpu: {{ .Values.ms.resources.requests.cpu }}
            limits:
              memory: {{ .Values.ms.resources.limits.memory }}
              cpu: {{ .Values.ms.resources.limits.cpu }}
          env:
            {{- range .Values.ms.envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          volumeMounts:
            {{- include "myhlp.dotenv_file_mount" . | nindent 10 -}}
          {{- if .Values.ms.probes.enabled }}
          livenessProbe:
            {{- if .Values.ms.probes.liveness.enabled }}
            httpGet:
              path: {{ .Values.ms.probes.liveness.path }}
              port: {{ .Values.ms.port }}
            initialDelaySeconds: {{ .Values.ms.probes.liveness.initialDelaySeconds | default .Values.ms.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.ms.probes.liveness.periodSeconds | default .Values.ms.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.ms.probes.liveness.timeoutSeconds | default .Values.ms.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.ms.probes.liveness.failureThreshold | default .Values.ms.probes.failureThreshold }}
            {{- end }}
          readinessProbe:
            {{- if .Values.ms.probes.readiness.enabled }}
            httpGet:
              path: {{ .Values.ms.probes.readiness.path }}
              port: {{ .Values.ms.port }}
            initialDelaySeconds: {{ .Values.ms.probes.readiness.initialDelaySeconds | default .Values.ms.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.ms.probes.readiness.periodSeconds | default .Values.ms.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.ms.probes.readiness.timeoutSeconds | default .Values.ms.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.ms.probes.readiness.failureThreshold | default .Values.ms.probes.failureThreshold }}
            {{- end }}
          {{- end }}
      volumes:
        {{- include "myhlp.volumes" . | nindent 8 -}}
