apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.ms.ns }}
  name: {{ .Values.ms.name }}
spec:
  selector:
    app: {{ .Values.ms.name }}
  type: {{ .Values.service.type }}
  # sessionAffinity: None
  # externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: {{ .Values.ms.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
