apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ms.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ms.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.ms.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
