{{- include "app.validateAll" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.app.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.app.replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.app.update.maxUnavailable | default 1 }}
      maxSurge: {{ .Values.app.update.maxSurge | default 0 }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false # prevent mount /run/**/secrets
      serviceAccountName: {{ .Values.vault.serviceAccountName }} # SA для vault
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      {{- if .Values.vault.restApiEnabled | default false -}}
      {{- include "vaultApiHlp.initContainer" . | nindent 6 -}}
      {{- end}}
      containers:
        - name: {{ include "app.fullname" . }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}@sha256:{{ .Values.app.image.digest }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true # Блокирует запись везде кроме /tmp и монтируемых volume
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: {{ .Values.app.resources.requests.memory }}
              cpu: {{ .Values.app.resources.requests.cpu }}
            limits:
              memory: {{ .Values.app.resources.limits.memory }}
              cpu: {{ .Values.app.resources.limits.cpu }}
          env:
          {{- if .Values.app.extraEnv }}
          {{- toYaml .Values.app.extraEnv | nindent 12 -}}
          {{- end }}
          {{- range $key, $value := .Values.app.envs }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.vault.vso.enabled }}
          envFrom:  # inject to env
            - secretRef:
                name: {{ include "app.fullname" . }}-secret
          {{- end }}
          volumeMounts:
            {{- if .Values.vault.restApiEnabled | default false -}}
            {{- include "vaultApiHlp.dotenv_file_mount" . | nindent 10 -}}
            {{- end }}
          {{- if .Values.app.probes.enabled }}
          livenessProbe:
            {{- if .Values.app.probes.liveness.enabled }}
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds | default .Values.app.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds | default .Values.app.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.app.probes.liveness.timeoutSeconds | default .Values.app.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.app.probes.liveness.failureThreshold | default .Values.app.probes.failureThreshold }}
            {{- end }}
          readinessProbe:
            {{- if .Values.app.probes.readiness.enabled }}
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds | default .Values.app.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds | default .Values.app.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.app.probes.readiness.timeoutSeconds | default .Values.app.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.app.probes.readiness.failureThreshold | default .Values.app.probes.failureThreshold }}
            {{- end }}
          {{- end }}
      volumes:
        {{- if .Values.vault.restApiEnabled | default false -}}
        {{- include "vaultApiHlp.volumes" . | nindent 8 -}}
        {{- end }}
