all:
  # example
  # vars: # можно расширить дополнительными переменными на этом уровне
  #   ansible_user: debian

  hosts: # перечисление всего списка хостов, которые с которыми предполагается взаимодействовать
    # example
    # vm1: # название хоста
    #   # список переменных конкретно для хоста vm1
    #   # переменные могут быть определены в group_vars/*.yaml, host_vars/*.yaml
    #   ansible_host: 192.168.99.100             # адрес хоста
    #   ansible_user: debian                     # non root логин хоста
    #   ansible_sudo_pass: "{{ vm1_sudo_pass }}" # переменная, берется из зашифрованного ansible-vault файла

    master_0: # если переопределяем в host_vars/*.yaml, то название файла .yaml должно совпадать с именем поля
      ansible_host: 192.168.99.100 # переменная определена на уровне host_vars/*.yaml
      # ansible_user: master # определена на уровне group_vars/*.yaml и неявно подставляется сюда
      ansible_become_pass: "{{ master_0_root_pass }}"

    worker_0:
      ansible_host: 192.168.99.101
      # ansible_user: worker1
      ansible_become_pass: "{{ worker_0_root_pass }}"

    worker_1:
      ansible_host: 192.168.99.102
      # ansible_user: worker2
      ansible_become_pass: "{{ worker_1_root_pass }}"

################################################################################

  children: # связывает хосты определенные выше в логические группы.
    all_nodes: # логическая группа
      hosts: # перечисляем список хостов, которые хотим добавить в эту логическую группу
        master_0:
        worker_0:
        worker_1:
      # example
      # vars: # можно расширить дополнительными переменными
      #   host_level_var_test1: 1
      #   host_level_var_test2: test

    masters:
      hosts:
        master_0:

    workers:
      hosts:
        worker_0:
        worker_1:
