FROM golang:1.23.5-alpine3.21

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

RUN apk add tzdata vim htop

WORKDIR /build
COPY version.json /build
COPY src          /build/src

# full static compilation
RUN export SERVICE_VERSION=$(grep 'version' ./version.json | cut -d '"' -f4 | tr '\n' '\0') && \
    go build \
        -ldflags="-s -w -X 'main.buildDate=$(date)' -X 'main.version=$SERVICE_VERSION' " \
        -o echo_server \
        src/main.go && cp ./echo_server /usr/local/bin

ENTRYPOINT [ "/bin/sh" ]
