# Muti-stage build
# First step
FROM golang:1.23.5-alpine3.21 AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /work
COPY version.json /work
COPY src          /work/src
COPY build.sh     /work

# full static compilation
RUN ./build.sh

# Second step
FROM alpine:3.21
COPY --from=builder /work/build/echo_server /usr/local/bin/echo_server
ENTRYPOINT [ "echo_server" ]
