apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "vault.fullname" . }}-cm"
  # namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  config.hcl: |
    disable_mlock = true
    ui            = {{ .Values.services.ui.enabled }}
    log_level     = "debug" # info
    listener "tcp" {
      address         = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable     = true
    }
    storage "raft" {
      path            = "/mnt/vault_data"
      tls_skip_verify = "true"
    }

  init.sh: |
    {{ .Files.Get "files/scripts/init.sh" | nindent 4 }}

  unseal.sh: |
    {{ .Files.Get "files/scripts/unseal.sh" | nindent 4 }}

  create_users.sh: |
    {{ .Files.Get "files/scripts/create_users.sh" | nindent 4 }}

  create_secrets.sh: |
    {{ .Files.Get "files/scripts/create_secrets.sh" | nindent 4 }}

  k8s_auth_method_upsert.sh: |
    {{ .Files.Get "files/scripts/k8s_auth_method_upsert.sh" | nindent 4 }}
