{{- if .Values.injector.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vault.fullname" . }}-agent-injector
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-agent-injector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  # MutatingWebhookConfiguration rights
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "patch"
      - "create"

  # # pods rights
  # - apiGroups: [""]
  #   resources: ["pods", "pods/status"]
  #   verbs: ["get", "list", "watch", "patch"]

  # # check SA token rights
  # - apiGroups: ["authentication.k8s.io"]
  #   resources: ["tokenreviews"]
  #   verbs: ["create"]

  # # Secret rights (certificates)
  # - apiGroups: [""]
  #   resources: ["secrets"]
  #   verbs: ["get", "list", "watch", "create", "update", "patch"]
{{- end }}
