{{ include "vault.checkNamespace" . }}

{{- range .Values.serviceAccounts }}
{{- if .create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "vault.labels" $ | nindent 4 }}
  {{- if .keepResource }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
{{- end }}
{{- end }}
