{{- if .Values.agent.enabled }}

# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.headless.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: api-port
      port: {{ .Values.services.headless.apiPort }}
      targetPort: api
    - name: cluster-port
      port: {{ .Values.services.headless.clusterPort }}
      targetPort: cluster
---
# UI access
{{- if .Values.services.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}
  type: {{ .Values.services.ui.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.ui.port }}
      {{- if eq .Values.services.ui.type "NodePort" }}
      nodePort: {{ .Values.services.ui.nodePort }}
      {{- end }}
{{- end }}

{{- end }}

