{{- if .Values.agent.enabled }}

{{- range $saName, $saConfig := .Values.serviceAccounts }}
{{- if $saConfig.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $saConfig.namespace | default $.Release.Namespace }}
  labels:
    {{- include "vault.labels" $ | nindent 4 }}
  {{- if $saConfig.keepResource }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
{{- end }}
{{- end }}

{{- end }}

