{{ include "vault.validate" . }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.services.headless.name }}
  podManagementPolicy: {{ .Values.agent.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.agent.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" $ | nindent 6 }}
  replicas: {{ .Values.agent.replicas }}
  revisionHistoryLimit: {{ .Values.agent.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.agent.name }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      {{- range .Values.agent.affinity.nodes }}
                      - {{ . | quote }}
                      {{- end }}
      securityContext:
        runAsUser: {{ .Values.agent.securityContext.pod.runAsUser }}
        runAsGroup: {{ .Values.agent.securityContext.pod.runAsGroup }}
        fsGroup: {{ .Values.agent.securityContext.pod.fsGroup }}
        sysctls: []
      containers:
        - name: vault
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          securityContext:
            runAsNonRoot: {{ .Values.agent.securityContext.container.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.agent.securityContext.container.allowPrivilegeEscalation }}
            capabilities:
              drop: {{ .Values.agent.securityContext.container.capabilities.drop }}
          command: ["/bin/sh", "-ec"]
          args:
            - |
              vault server -config=/vault/config
          lifecycle:
            {{- if .Values.agent.lifecycle.postStart.enabled }}
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep {{ .Values.agent.lifecycle.postStart.sleepSeconds | default 5 }}
                    {{- range .Values.agent.lifecycle.postStart.scripts }}
                    {{ . }} >> {{ $.Values.agent.lifecycle.postStart.logPath | default "/tmp/log" }} 2>&1
                    {{- end }}
            {{- end }}
            {{- if .Values.agent.lifecycle.preStop.enabled }}
            preStop:
              exec:
                command:
                  - |
                    {{- range .Values.agent.lifecycle.preStop.commands }}
                    {{ . }}
                    {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.agent.ports.api }}
              name: api
              protocol: TCP
            - containerPort: {{ .Values.agent.ports.cluster }}
              name: cluster
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.agent.env.TZ | quote }}
            - name: KEYS_FILE
              value: "{{ .Values.agent.fsMountPoint }}/vault_data/keys"
            - name: SKIP_CHOWN
              value: {{ .Values.agent.env.SKIP_CHOWN | quote }}
            - name: SKIP_SETCAP
              value: {{ .Values.agent.env.SKIP_SETCAP | quote }}
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_RAFT_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_ADDR
              value: "http://$(VAULT_RAFT_NODE_ID).{{ .Values.services.headless.name }}.{{ .Values.global.namespace | default .Release.Namespace }}.svc:{{ .Values.agent.ports.api }}"
            - name: VAULT_API_ADDR
              value: "http://$(VAULT_RAFT_NODE_ID).{{ .Values.services.headless.name }}.{{ .Values.global.namespace | default .Release.Namespace }}.svc:{{ .Values.agent.ports.api }}"
            - name: VAULT_CLUSTER_ADDR
              value: "http://$(VAULT_RAFT_NODE_ID).{{ .Values.services.headless.name }}.{{ .Values.global.namespace | default .Release.Namespace }}.svc:{{ .Values.agent.ports.cluster }}"
            - name: HOME
              value: {{ .Values.agent.env.HOME }}
          livenessProbe:
            httpGet:
              path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
              port: {{ .Values.agent.ports.api }}
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -ec
                - |
                  vault status -tls-skip-verify
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "{{ .Values.agent.fsMountPoint }}/vault_data"
            - name: config
              mountPath: /vault/config
            - name: scripts
              mountPath: /vault/scripts
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configMap.vault.name }}
            items:
              - key: config.hcl
                path: config.hcl
        - name: scripts
          configMap:
            name: {{ .Values.configMap.vault.name }}
            items:
              - key: init.sh
                path: init.sh
              - key: unseal.sh
                path: unseal.sh
              - key: create_users.sh
                path: create_users.sh
              - key: create_secrets.sh
                path: create_secrets.sh
              - key: vars.sh
                path: vars.sh
              - key: read_policies.sh
                path: read_policies.sh
              - key: k8s_auth_method_upsert.sh
                path: upsert_auth_method.sh
            defaultMode: 0110
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.agent.volumeClaimTemplates.data.storageClassName }}
        accessModes:
          {{- toYaml .Values.agent.volumeClaimTemplates.data.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.agent.volumeClaimTemplates.data.size }}
