{{- range $tlsConfig := .Values.ingress.tls }}
{{- if and $tlsConfig.enabled $tlsConfig.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tlsConfig.secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault.labels" $ | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ $tlsConfig.secret.crt }}
  tls.key: {{ $tlsConfig.secret.key }}
{{- end }}
{{- end }}
