{{- if and .Values.services.ui.enabled (eq .Values.services.ui.type "ClusterIP") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    # LB type
    nginx.ingress.kubernetes.io/lb-method: "round_robin"
    # Redirect to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- $enabledTls := list }}
  {{- range .Values.ingress.tls }}
    {{- if .enabled }}
      {{- $enabledTls = append $enabledTls . }}
    {{- end }}
  {{- end }}
  {{- if $enabledTls }}
  tls:
    {{- range $enabledTls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Values.services.ui.name }}
                port:
                  number: {{ $.Values.services.ui.port }}
          {{- end }}
    {{- end }}
{{- end }}
