{{- if .Values.vso.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault.name" . }}-secrets-operator
  namespace: {{ .Values.vso.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-secrets-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
