resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.14.3/deploy/static/provider/baremetal/deploy.yaml
  - ./deployment.yaml

patches:
  - target:  # delete
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
  - path: service-patch.yaml  # patch a existing manifest
