{{- if .Values.vault.vso.enabled -}}
{{- $envTemplate := `{{- range $k,$v:=.Secrets}}{{$k}}={{$v}}{{"\n"}}{{- end}}` }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  namespace: {{ .Values.app.namespace }}
spec:
  vaultAuthRef: {{ include "app.fullname" . }}-auth
  type: {{ .Values.vault.secret.type }}
  mount: {{ .Values.vault.secret.enginePath }}
  path: {{ .Values.vault.secret.name }}
  refreshAfter: 30s
  destination:
    create: true
    name: {{ include "app.fullname" .  }}-secret
    {{- if .Values.vault.vso.injectToFile }}
    transformation:
      # excludes:
      #  - .*
      templates:
        env:
          name: env
          text: |
            {{ $envTemplate }}
    {{- end }}
{{- end }}
